# Generated by Django 3.2.14 on 2022-07-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220729_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='month',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
